version: '3.9'
services:
  service-db:
    image: mysql:8.0.26
    container_name: singidol
    restart: always
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=apap
    ports:
      - 3306:3306
    expose:
      - '3306'
    volumes:
      - service-db:/var/lib/mysql

volumes:
  service-db:
